services:
    email-page:
        image: jordanroher/email-page
        container_name: email-page
        ports:
            - 3000:3000
        environment:
            - SMTP_HOST=smtp.example.com
            - SMTP_PORT=587
            - SMTP_USER=username
            - SMTP_PASS=password
            - DOMAIN_NAME=email-page.example.com
            - EMAIL_FROM=email-page@example.com
            - EMAIL_TO=notifications@example.com
        volumes:
            - data:/etc/email-page/data

volumes:
    data:
